### ISSUE TITLE
First comments

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans/signs-data-viewer#2]
> Map is slow. Could use the plain map as default, and have a choice to change to satellite.  
  
- [x] Make Streets the default with toggle for VT Ortho  

> Could you add URL parameters to get a point show on the map based on the latitude and longitude? This could help the annotator to locate the sign on the map.

- [x] Draw a point on map render based on querystring

**Comment by TheMapSmith** [comment]
cc @jocooler for remaining checkbox above

**Comment by jocooler** [comment]
Do you want it to also draw the point where they clicked when they're trying to locate a sign or where they want the sign to be?

**Comment by TheMapSmith** [comment]
Sure

**Comment by jocooler** [comment]
Resolved Streets as Default with VT Ortho toggle in a868c22d35dd4b9e8fb60473480bf4d83703ff34

I believe the slowness is because they built the basemap in VT State Plan Meters and it's re-projecting on every request.

**Comment by jocooler** [comment]
Resolved Draw Click Point in bc8f2d772c4e3ce334b8246f007cf6f8c85c7d00
