### ISSUE TITLE
Zoomlevel querystring not handled

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans/signs-data-viewer#3]
Why isn't it reading it?

**Comment by TheMapSmith** [comment]
@jocooler I found a variable name mismatch, but for some reason it's not handling the zoom level. can you take a peek?

**Comment by jocooler** [comment]
Try now. I had a limited number of LODs enabled.

**Comment by jocooler** [comment]
@TheMapSmith This seems to be working, so I'm going to close.
